# COGS 108 - Data Checkpoint

# Names

- Colby Hillers
- Calvin Cheung
- Jorge Mendoza
- Javon Maxie
- Hoang Nguyen

<a id='research_question'></a>
# Research Question

In the NBA, over the regular season, do international players have a higher Efficiency Metric (EFF) than players born in the United States?

# Dataset(s)


- Dataset Name: Basketball Players Stats. Extended analysis.
- Link to the dataset: https://www.kaggle.com/isaienkov/basketball-players-stats-extended-analysis/data
- Number of observations: 53,949

This dataset includes the necessary stats and attributes for us to calculate the EFF for each player in the NBA since the 1999-2000 season.

# Setup

In [ ]:
## YOUR CODE HERE
import numpy as np
import pandas as pd

# Data Cleaning

Describe your data cleaning steps here.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

In [ ]:
df = pd.read_csv('players_stats_by_season_full_details.csv')
df

                      League       Season  ... draft_pick             draft_team
0                        NBA  1999 - 2000  ...        1.0          Orlando Magic
1                        NBA  1999 - 2000  ...        5.0  Golden State Warriors
2                        NBA  1999 - 2000  ...       13.0              Utah Jazz
3                        NBA  1999 - 2000  ...        1.0    Philadelphia Sixers
4                        NBA  1999 - 2000  ...        2.0    Seattle SuperSonics
...                      ...          ...  ...        ...                    ...
53944  Ukrainian-Superleague  2019 - 2020  ...        NaN                    NaN
53945  Ukrainian-Superleague  2019 - 2020  ...        NaN                    NaN
53946  Ukrainian-Superleague  2019 - 2020  ...        NaN                    NaN
53947  Ukrainian-Superleague  2019 - 2020  ...        NaN                    NaN
53948  Ukrainian-Superleague  2019 - 2020  ...        NaN                    NaN

[53949 rows x 34 columns]

In [ ]:
# checking the shape of the dataset
df.shape

(53949, 34)

In [ ]:
null_rows = df.isnull().any(axis=1).sum()
null_rows

46113

In [ ]:
df = df[(df.Stage == 'Regular_Season')]
df

      League       Season  ... draft_pick              draft_team
0        NBA  1999 - 2000  ...        1.0           Orlando Magic
1        NBA  1999 - 2000  ...        5.0   Golden State Warriors
2        NBA  1999 - 2000  ...       13.0               Utah Jazz
3        NBA  1999 - 2000  ...        1.0     Philadelphia Sixers
4        NBA  1999 - 2000  ...        2.0     Seattle SuperSonics
...      ...          ...  ...        ...                     ...
51971    NBA  2019 - 2020  ...        NaN                     NaN
51972    NBA  2019 - 2020  ...       18.0          Indiana Pacers
51973    NBA  2019 - 2020  ...       25.0  Portland Trail Blazers
51974    NBA  2019 - 2020  ...        NaN                     NaN
51975    NBA  2019 - 2020  ...        8.0    Los Angeles Clippers

[4658 rows x 34 columns]

In [ ]:
df = df.iloc[:, :30]
df

      League       Season  ... weight_kg              nationality
0        NBA  1999 - 2000  ...     147.0            United States
1        NBA  1999 - 2000  ...     100.0            United States
2        NBA  1999 - 2000  ...     120.0            United States
3        NBA  1999 - 2000  ...      75.0            United States
4        NBA  1999 - 2000  ...      82.0            United States
...      ...          ...  ...       ...                      ...
51971    NBA  2019 - 2020  ...      91.0                Australia
51972    NBA  2019 - 2020  ...     111.0                  Georgia
51973    NBA  2019 - 2020  ...     100.0            United States
51974    NBA  2019 - 2020  ...      99.0            United States
51975    NBA  2019 - 2020  ...     100.0  United States / Nigeria

[4658 rows x 30 columns]

In [ ]:
df = df.drop(['Team', 'ORB', 'DRB', '3PM', '3PA', 'birth_year', 'birth_month', 'birth_date','height', 'height_cm', 'weight', 'weight_kg'],  axis = 1)
df

      League       Season           Stage  ...  BLK   PTS              nationality
0        NBA  1999 - 2000  Regular_Season  ...  239  2344            United States
1        NBA  1999 - 2000  Regular_Season  ...   92  2107            United States
2        NBA  1999 - 2000  Regular_Season  ...   71  2095            United States
3        NBA  1999 - 2000  Regular_Season  ...    5  1989            United States
4        NBA  1999 - 2000  Regular_Season  ...   18  1982            United States
...      ...          ...             ...  ...  ...   ...                      ...
51971    NBA  2019 - 2020  Regular_Season  ...    2   177                Australia
51972    NBA  2019 - 2020  Regular_Season  ...   37   172                  Georgia
51973    NBA  2019 - 2020  Regular_Season  ...   14   172            United States
51974    NBA  2019 - 2020  Regular_Season  ...   12   104            United States
51975    NBA  2019 - 2020  Regular_Season  ...    8    78  United States / Nigeria

[4658 rows x 18 columns]

In [ ]:
df = df.assign(Missed_FG = df['FGA'] - df['FGM'])
df

      League       Season  ...              nationality Missed_FG
0        NBA  1999 - 2000  ...            United States       709
1        NBA  1999 - 2000  ...            United States       908
2        NBA  1999 - 2000  ...            United States       724
3        NBA  1999 - 2000  ...            United States      1004
4        NBA  1999 - 2000  ...            United States       919
...      ...          ...  ...                      ...       ...
51971    NBA  2019 - 2020  ...                Australia       113
51972    NBA  2019 - 2020  ...                  Georgia        80
51973    NBA  2019 - 2020  ...            United States        86
51974    NBA  2019 - 2020  ...            United States        34
51975    NBA  2019 - 2020  ...  United States / Nigeria        61

[4658 rows x 19 columns]

In [ ]:
df = df.assign(Missed_FT = df['FTA'] - df['FTM'])
df

      League       Season  ... Missed_FG Missed_FT
0        NBA  1999 - 2000  ...       709       392
1        NBA  1999 - 2000  ...       908       115
2        NBA  1999 - 2000  ...       724       150
3        NBA  1999 - 2000  ...      1004       178
4        NBA  1999 - 2000  ...       919       112
...      ...          ...  ...       ...       ...
51971    NBA  2019 - 2020  ...       113         5
51972    NBA  2019 - 2020  ...        80         9
51973    NBA  2019 - 2020  ...        86        16
51974    NBA  2019 - 2020  ...        34         9
51975    NBA  2019 - 2020  ...        61        10

[4658 rows x 20 columns]

In [ ]:
df = df.assign(EEF = (df['PTS'] + df['REB'] + df['AST'] + df['STL'] + df['BLK'] - df['Missed_FG'] - df['Missed_FT'] - df['TOV'])/ df['GP'] )
df

      League       Season           Stage  ... Missed_FG  Missed_FT        EEF
0        NBA  1999 - 2000  Regular_Season  ...       709        392  33.822785
1        NBA  1999 - 2000  Regular_Season  ...       908        115  23.243902
2        NBA  1999 - 2000  Regular_Season  ...       724        150  27.109756
3        NBA  1999 - 2000  Regular_Season  ...      1004        178  18.871429
4        NBA  1999 - 2000  Regular_Season  ...       919        112  26.329268
...      ...          ...             ...  ...       ...        ...        ...
51971    NBA  2019 - 2020  Regular_Season  ...       113          5   4.859649
51972    NBA  2019 - 2020  Regular_Season  ...        80          9   4.277778
51973    NBA  2019 - 2020  Regular_Season  ...        86         16   4.416667
51974    NBA  2019 - 2020  Regular_Season  ...        34          9   6.450000
51975    NBA  2019 - 2020  Regular_Season  ...        61         10   6.888889

[4658 rows x 21 columns]

In [ ]:
df.describe()

                GP          MIN  ...    Missed_FT          EEF
count  4658.000000  4658.000000  ...  4658.000000  4658.000000
mean     73.176471  1950.109489  ...    47.335337    12.725857
std       8.751048   637.080061  ...    39.224291     5.787311
min       1.000000     0.700000  ...     0.000000    -1.000000
25%      69.000000  1473.000000  ...    22.000000     8.408797
50%      75.000000  1955.100000  ...    37.000000    11.701852
75%      80.000000  2439.675000  ...    61.000000    16.148921
max      85.000000  3485.000000  ...   473.000000    35.250000

[8 rows x 16 columns]